# Generated by Django 5.2.3 on 2025-07-01 14:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Upload Batch',
                'verbose_name_plural': 'Data Upload Batches',
                'db_table': 'data_upload_batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField(unique=True, verbose_name='Serial Number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('sponsorship', models.CharField(choices=[('Gov', 'Government'), ('Private', 'Private'), ('Scholarship', 'Scholarship')], max_length=20)),
                ('session', models.CharField(help_text='Academic session', max_length=20)),
                ('retakes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('csc1201', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CSC1201 Score')),
                ('csc1202', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CSC1202 Score')),
                ('csc1203', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CSC1203 Score')),
                ('bsm1201', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='BSM1201 Score')),
                ('ict1201', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='ICT1201 Score')),
                ('remarks', models.CharField(choices=[('NP', 'Not Passed'), ('PP', 'Passed'), ('AB', 'Absent')], max_length=10)),
                ('dropped', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Record',
                'verbose_name_plural': 'Student Records',
                'db_table': 'student_records',
                'ordering': ['sn'],
                'indexes': [models.Index(fields=['session'], name='student_rec_session_f02c7e_idx'), models.Index(fields=['remarks'], name='student_rec_remarks_6a7228_idx'), models.Index(fields=['dropped'], name='student_rec_dropped_ac8bd8_idx'), models.Index(fields=['gender'], name='student_rec_gender_4ac332_idx')],
            },
        ),
    ]
