# Generated by Django 5.2.3 on 2025-07-01 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='bsm1201',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='BSM1201 Score'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='csc1201',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CSC1201 Score'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='csc1202',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CSC1202 Score'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='csc1203',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CSC1203 Score'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='ict1201',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='ICT1201 Score'),
        ),
    ]
